FROM pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.7
LABEL maintainer="tongjinle"
# 设置apt、conda、pip代理镜像
#RUN wget https://tuna.moe/oh-my-tuna/oh-my-tuna.py && python oh-my-tuna.py
RUN git clone https://github.com/tuna/oh-my-tuna.git && python oh-my-tuna/oh-my-tuna.py
# 开启终端色彩
ENV TERM=xterm-256color
# apt安装常用软件
RUN apt-get update && apt-get install -y --no-install-recommends \
         build-essential \
         cmake \
         git \
         curl \
         ca-certificates \
         sudo \
         openssh-server \
         bash-completion \
         vim \
         zsh \
         tmux \
         libsndfile1 \
         gcc \
         make \
         autoconf \
         openssl \
         apt-transport-https && \
         rm -rf /var/lib/apt/lists/* && apt-get clean

# 新建用户并用 fixuid 管理 uid
ENV USERNAME="docker"
ENV PASSWD="123456"
RUN useradd --create-home --no-log-init --shell /bin/zsh ${USERNAME} && \
    adduser ${USERNAME} sudo && \
    echo "${USERNAME}:${PASSWD}" | chpasswd
RUN USER=${USERNAME} && \
    GROUP=${USERNAME} && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.4.1/fixuid-0.4.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml

USER ${USERNAME}:${USERNAME}

WORKDIR /home/${USERNAME}

# 安装配置oh-my-zsh
RUN sh -c "$(curl -fsSL https://gitee.com/mirrors/oh-my-zsh/raw/master/tools/install.sh)" && \
    git clone https://github.com/zsh-users/zsh-autosuggestions .oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git .oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    sed -i "s/^plugins=.*$/plugins=(git colorize cp copydir z zsh-autosuggestions zsh-syntax-highlighting)/" .zshrc 

# 配置环境变量，使ssh连接时env也生效
RUN sed -i '$a\export $(cat /proc/1/environ |tr "\\0" "\\n" | xargs)' .zshrc

ENV PATH="/home/${USERNAME}/.local/bin:$PATH"
RUN git clone https://github.com/tuna/oh-my-tuna.git && python oh-my-tuna/oh-my-tuna.py
#RUN wget https://tuna.moe/oh-my-tuna/oh-my-tuna.py && python oh-my-tuna.py
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 22
ENTRYPOINT ["fixuid"]
CMD echo ${PASSWD} | sudo -S service ssh start && /bin/zsh
